- name: Create symlink to tmux config
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "~/.tmux.conf"
    state: link

- name: Add tmux zsh helpers 
  ansible.builtin.blockinfile:
    path: ~/.zshrc.ansible-managed
    marker: "# {mark} --> {{ role_name }}"
    marker_begin: "start"
    marker_end: "end"
    block: "{{ lookup('ansible.builtin.file', 'files/tmux.zsh') }}"
    create: true
